[workspace]
members = [
    "lib/ic_call_api",
    "lib/ic_call_backend",
    "lib/ic_call_client",
    "lib/ic_ledger",
    "lib/ic_identity",
    "lib/ic_governance",
]

[profile.release]
lto = true
opt-level = "z"
codegen-units = 1
